name: Run format check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: echo "VIRTUAL_ENV=${Python_ROOT_DIR}" >> $GITHUB_ENV
      - run: pip install uv
      - name: Install dependencies
        working-directory: ./backend
        run: uv pip install -r requirements.dev.in
      - name: Run lint check
        working-directory: ./backend
        run: ruff check .
      - name: Run  format check
        working-directory: ./backend
        run: ruff format . --check
