name: Run type check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - name: Install dependencies
        run: poetry install --no-ansi --no-interaction
      - name: Run type check
        run: mypy inertia
